version: '3'

services:
    # =-=-=-=-= GOLANG =-=-=-=-=
    golang:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: FAGolang
      ports:
        - "3000:3000"
      volumes:
        - .:/go/src/github.com/lovohh/FoodAcidityAPI/